/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.filmeDAO;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import model.filme;
import model.usuario;

/**
 *
 * @author CARLOSHENRIQUECARDOZ
 */
public class CadastrarGenero extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastrarGenero.class.getName());

    /**
     * Creates new form CadastrarGenero
     */
    public CadastrarGenero() {
        initComponents();
       getContentPane().setBackground(new java.awt.Color(60, 60, 60));
       this.setLocationRelativeTo(null);

       CarregarTabela();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cadastrarbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        generoTxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelagen = new javax.swing.JTable();
        deletarbtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRAR GÊNERO");

        cadastrarbtn.setBackground(new java.awt.Color(51, 102, 0));
        cadastrarbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrarbtn.setText("CADASTRAR");
        cadastrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GÊNERO:");

        generoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoTxtActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(100, 100, 100));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("VOLTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabelagen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Gêneros"
            }
        ));
        jScrollPane1.setViewportView(tabelagen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        deletarbtn.setBackground(new java.awt.Color(255, 51, 51));
        deletarbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deletarbtn.setText("DELETAR");
        deletarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarbtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("DESENVOLVIDO POR CARLOS HENRIQUE CARDOZO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(deletarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cadastrarbtn))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(generoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarbtn)
                    .addComponent(jButton2))
                .addGap(7, 7, 7)
                .addComponent(deletarbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoTxtActionPerformed

    private void cadastrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarbtnActionPerformed

    String nomeGenero = generoTxt.getText();

    
    if (nomeGenero.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, digite o nome do gênero.", "ERRO", JOptionPane.ERROR_MESSAGE);
    } else {
        try {
            filmeDAO fDao = new filmeDAO(); 

            model.genero novoGenero = new model.genero();
            
            novoGenero.nome = nomeGenero; 

            fDao.cadastrargen(novoGenero); 

            JOptionPane.showMessageDialog(this, "Gênero cadastrado com sucesso!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            
            CarregarTabela();
            
            generoTxt.setText("");
            generoTxt.requestFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_cadastrarbtnActionPerformed

    private void deletarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarbtnActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelagen.getSelectedRow();

    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecione um gênero na tabela para deletar.", "Aviso", JOptionPane.WARNING_MESSAGE);
    } else {
        int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este gênero?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(tabelagen.getValueAt(linhaSelecionada, 0).toString());

                filmeDAO fDao = new filmeDAO();
                fDao.deletarGenero(id); 

                JOptionPane.showMessageDialog(this, "Gênero excluído com sucesso!");

                CarregarTabela(); 
                generoTxt.setText("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao deletar: " + e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    }//GEN-LAST:event_deletarbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MenuPrincipal mp = new MenuPrincipal();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {
    new MenuPrincipal().setVisible(true);
    this.dispose();
}

private void LimparFormulario() {
    generoTxt.setText("");
    generoTxt.requestFocus();
}

private void CarregarTabela() {
    try {
        filmeDAO dao = new filmeDAO();
        List<model.genero> listaGeneros = dao.listarGenerosLimpos(); 
        
        String[][] dados = new String[listaGeneros.size()][2];
        
        for (int i = 0; i < listaGeneros.size(); i++) {
            dados[i][0] = String.valueOf(listaGeneros.get(i).getId());
            dados[i][1] = listaGeneros.get(i).nome;
        }
        
        String[] colunas = {"ID", "Gênero"};
        tabelagen.setModel(new javax.swing.table.DefaultTableModel(dados, colunas));
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());
    }
    }
     

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastrarGenero().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarbtn;
    private javax.swing.JButton deletarbtn;
    private javax.swing.JTextField generoTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelagen;
    // End of variables declaration//GEN-END:variables
}
