/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.filmeDAO;
import java.util.List;
import javax.swing.JOptionPane;
import model.filme;
import java.sql.SQLException;

/**
 *
 * @author CARLOSHENRIQUECARDOZ
 */
public class ListarFilmes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListarFilmes.class.getName());

    /**
     * Creates new form ListarFilmes
     */
    public ListarFilmes() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(60, 60, 60));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listartodosbtn = new javax.swing.JButton();
        filtrargenbtn = new javax.swing.JButton();
        filtrarstatusbtn = new javax.swing.JButton();
        voltarbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelalistar = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTAR FILMES");

        listartodosbtn.setBackground(new java.awt.Color(153, 153, 153));
        listartodosbtn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        listartodosbtn.setText("LISTAR TODOS");
        listartodosbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listartodosbtnActionPerformed(evt);
            }
        });

        filtrargenbtn.setBackground(new java.awt.Color(153, 153, 153));
        filtrargenbtn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        filtrargenbtn.setText("FILTRAR POR GÊNERO");
        filtrargenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrargenbtnActionPerformed(evt);
            }
        });

        filtrarstatusbtn.setBackground(new java.awt.Color(153, 153, 153));
        filtrarstatusbtn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        filtrarstatusbtn.setText("FILTRAR POR STATUS");
        filtrarstatusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarstatusbtnActionPerformed(evt);
            }
        });

        voltarbtn.setBackground(new java.awt.Color(100, 100, 100));
        voltarbtn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        voltarbtn.setText("VOLTAR");
        voltarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarbtnActionPerformed(evt);
            }
        });

        tabelalistar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Gênero", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelalistar);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("DESENVOLVIDO POR CARLOS HENRIQUE CARDOZO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(voltarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listartodosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(filtrarstatusbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filtrargenbtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filtrargenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtrarstatusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listartodosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voltarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtrargenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrargenbtnActionPerformed
        // TODO add your handling code here:
        filtrarFilmesPorGenero();

    }//GEN-LAST:event_filtrargenbtnActionPerformed

    private void filtrarstatusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarstatusbtnActionPerformed
        // TODO add your handling code here:
        filtrarFilmesPorStatus();
    }//GEN-LAST:event_filtrarstatusbtnActionPerformed

    private void listartodosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listartodosbtnActionPerformed
        // TODO add your handling code here:
        carregarTudo();
    }//GEN-LAST:event_listartodosbtnActionPerformed

    private void voltarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarbtnActionPerformed
        // TODO add your handling code here:
        MenuPrincipal mp = new MenuPrincipal();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarbtnActionPerformed

    private void filtrarFilmesPorGenero() {
    String generoBusca = JOptionPane.showInputDialog(this, "Digite o gênero que deseja buscar:");

    if (generoBusca != null) { 
        try {
            filmeDAO dao = new filmeDAO();
            List<filme> listaFilmes = dao.listarPorGenero(generoBusca); 

            String[][] dados = new String[listaFilmes.size()][5];

            for (int i = 0; i < listaFilmes.size(); i++) {
                filme f = listaFilmes.get(i);
                dados[i][0] = String.valueOf(f.getId_filme());
                dados[i][1] = f.getTitulo();
                dados[i][2] = f.getGenero().nome;
                dados[i][3] = f.getStatus();
                dados[i][4] = String.valueOf(f.getAno_lancamento());
            }

            String[] colunas = {"ID", "Título", "Gênero", "Status", "Ano"};
            tabelalistar.setModel(new javax.swing.table.DefaultTableModel(dados, colunas));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao filtrar: " + e.getMessage());
        }
    }
}
    
    private void filtrarFilmesPorStatus() {
    String[] opcoes = {"disponivel", "locado"};
    String statusBusca = (String) JOptionPane.showInputDialog(this, 
            "Selecione o status:", "Filtro de Status", 
            JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
    if (statusBusca != null) {
        try {
            filmeDAO dao = new filmeDAO();
            List<model.filme> listaFilmes = dao.listarPorStatus(statusBusca); 

            String[][] dados = new String[listaFilmes.size()][5];
            for (int i = 0; i < listaFilmes.size(); i++) {
                model.filme f = listaFilmes.get(i);
                dados[i][0] = String.valueOf(f.getId_filme());
                dados[i][1] = f.getTitulo();
                dados[i][2] = (f.getGenero() != null) ? f.getGenero().nome : "Sem Gênero";
                dados[i][3] = f.getStatus();
                dados[i][4] = String.valueOf(f.getAno_lancamento());
            }

            String[] colunas = {"ID", "Título", "Gênero", "Status", "Ano"};
            tabelalistar.setModel(new javax.swing.table.DefaultTableModel(dados, colunas));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao filtrar status: " + e.getMessage());
        }
    }
    }
    
    private void carregarTudo() {
    try {
        List<filme> lista = new filmeDAO().listar();
        String[][] dados = new String[lista.size()][5];

        for (int i = 0; i < lista.size(); i++) {
            filme f = lista.get(i);
            dados[i] = new String[]{
                String.valueOf(f.getId_filme()), 
                f.getTitulo(), 
                (f.getGenero() != null) ? f.getGenero().nome : "", 
                f.getStatus(), 
                String.valueOf(f.getAno_lancamento())
            };
        }

        tabelalistar.setModel(new javax.swing.table.DefaultTableModel(dados, 
            new String[]{"ID", "Título", "Gênero", "Status", "Ano"}));
            
    } catch (SQLException e) {
        System.out.println("Erro: " + e.getMessage());
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListarFilmes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filtrargenbtn;
    private javax.swing.JButton filtrarstatusbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listartodosbtn;
    private javax.swing.JTable tabelalistar;
    private javax.swing.JButton voltarbtn;
    // End of variables declaration//GEN-END:variables
}
