/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.usuarioDAO;
import model.usuario;

/**
 *
 * @author CARLOSHENRIQUECARDOZ
 */



public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal_sncf
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(60, 60, 60));
        
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnEstatisticas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BtnExport = new javax.swing.JButton();
        BtnCadastrarFilme = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();
        BtnCadastrarGen = new javax.swing.JButton();
        BtnImport = new javax.swing.JButton();
        BtnListar = new javax.swing.JButton();
        BtnAlterarStatus = new javax.swing.JButton();
        BtnDeletar = new javax.swing.JButton();
        BtnAlocar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("DESENVOLVIDO POR CARLOS HENRIQUE CARDOZO");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cc61c927-bde4-451c-b249-f7c87d40dc1d.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMINISTRAÇÃO E DADOS");

        BtnEstatisticas.setBackground(new java.awt.Color(42, 98, 154));
        BtnEstatisticas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtnEstatisticas.setText("Estatísticas Gerais");
        BtnEstatisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEstatisticasActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("GERENCIAMENTO DE CONTEÚDO");

        BtnExport.setBackground(new java.awt.Color(42, 98, 154));
        BtnExport.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtnExport.setText("Exportação");
        BtnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExportActionPerformed(evt);
            }
        });

        BtnCadastrarFilme.setBackground(new java.awt.Color(42, 98, 154));
        BtnCadastrarFilme.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtnCadastrarFilme.setText("Cadastrar Filmes");
        BtnCadastrarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarFilmeActionPerformed(evt);
            }
        });

        BtnSair.setBackground(new java.awt.Color(100, 100, 100));
        BtnSair.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtnSair.setText("Sair");
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        BtnCadastrarGen.setBackground(new java.awt.Color(42, 98, 154));
        BtnCadastrarGen.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtnCadastrarGen.setText("Cadastrar Gênero");
        BtnCadastrarGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarGenActionPerformed(evt);
            }
        });

        BtnImport.setBackground(new java.awt.Color(42, 98, 154));
        BtnImport.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtnImport.setText("Importação");
        BtnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImportActionPerformed(evt);
            }
        });

        BtnListar.setBackground(new java.awt.Color(42, 98, 154));
        BtnListar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtnListar.setText("Listar Filmes");
        BtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarActionPerformed(evt);
            }
        });

        BtnAlterarStatus.setBackground(new java.awt.Color(42, 98, 154));
        BtnAlterarStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtnAlterarStatus.setText("Alterar Status");
        BtnAlterarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarStatusActionPerformed(evt);
            }
        });

        BtnDeletar.setBackground(new java.awt.Color(42, 98, 154));
        BtnDeletar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtnDeletar.setText("Deletar Filme");
        BtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletarActionPerformed(evt);
            }
        });

        BtnAlocar.setBackground(new java.awt.Color(42, 98, 154));
        BtnAlocar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BtnAlocar.setText("Alocação");
        BtnAlocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlocarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtnCadastrarFilme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnCadastrarGen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnAlterarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtnEstatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnAlocar, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCadastrarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCadastrarGen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAlterarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAlocar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEstatisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEstatisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEstatisticasActionPerformed
        // TODO add your handling code here:
        Estatisticas e = new Estatisticas();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnEstatisticasActionPerformed

    private void BtnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExportActionPerformed
        // TODO add your handling code here:
        Exportação export = new Exportação();
        export.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnExportActionPerformed

    private void BtnCadastrarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarFilmeActionPerformed
        // TODO add your handling code here:
        
        CadastrarFilme cf = new CadastrarFilme();
        cf.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BtnCadastrarFilmeActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        // TODO add your handling code here:
        
       System.exit(0);
        
    }//GEN-LAST:event_BtnSairActionPerformed

    private void BtnCadastrarGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarGenActionPerformed
        // TODO add your handling code here:
        CadastrarGenero cg = new CadastrarGenero();
        cg.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BtnCadastrarGenActionPerformed

    private void BtnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImportActionPerformed
        // TODO add your handling code here:
        Importação imp = new Importação();
        imp.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnImportActionPerformed

    private void BtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarActionPerformed
        // TODO add your handling code here:
        ListarFilmes listar = new ListarFilmes();
        listar.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnListarActionPerformed

    private void BtnAlterarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarStatusActionPerformed
        // TODO add your handling code here:
        AlterarStatus as = new AlterarStatus();
        as.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnAlterarStatusActionPerformed

    private void BtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletarActionPerformed
        // TODO add your handling code here:
        DeletarFilme df = new DeletarFilme();
        df.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnDeletarActionPerformed

    private void BtnAlocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlocarActionPerformed
        // TODO add your handling code here:
        Alocação al = new Alocação();
        al.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnAlocarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlocar;
    private javax.swing.JButton BtnAlterarStatus;
    private javax.swing.JButton BtnCadastrarFilme;
    private javax.swing.JButton BtnCadastrarGen;
    private javax.swing.JButton BtnDeletar;
    private javax.swing.JButton BtnEstatisticas;
    private javax.swing.JButton BtnExport;
    private javax.swing.JButton BtnImport;
    private javax.swing.JButton BtnListar;
    private javax.swing.JButton BtnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
